on:
  push:
    tags:
      - patch

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump patch
        run: ./bump_version.sh PATCH $(($PATCH + 1))
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PATCH: ${{ vars.PATCH }}