on:
  push:
    tags:
      - minor

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump patch
        run: ./bump_version.sh PATCH 0
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Bump minor
        run: ./bump_version.sh MINOR $(($MINOR + 1)
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PATCH: ${{ vars.MINOR }}