on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump the version'
        required: false
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump patch
        if: ${{ github.event.inputs.bump == 'patch' }}
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/variables/NAME \
            -d '{"name":"PATCH","value":$(($PATCH + 1))}'
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PATCH: ${{ vars.PATCH }}

      - name: Bump minor
        if: ${{ github.event.inputs.bump == 'minor' }}
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/variables/NAME \
            -d '{"name":"MINOR","value":$(($MINOR + 1))}'
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PATCH: ${{ vars.MINOR }}
        
      - name: Bump major
        if: ${{ github.event.inputs.bump == 'major' }}
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/actions/variables/NAME \
            -d '{"name":"MAJOR","value":$(($MAJOR + 1))}'
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PATCH: ${{ vars.MAJOR }}